# Pods are the smallest deployable units of computing that you can create and manage in Kubernetes
apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
  - name: nginx-c1
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    env:
    - name: WebServer
      value: "nginx"
    - name: Environment
      value: "sandbox"
    - name: DbPort
      value: "5432"
    - name: DbHost
      value: "sample.test.svc.cluster.local"
