# What is a resource quota in kubernetes ?

# We have one roboshop-test cluster and testing on this cluster is done by catalogue, cart, payment, shipping and user teams ( namespaces ) 
# Each team is using the same cluster for testing their application. 

# Now if we want to enforce that "Catalogue Team" to use only 50CPU and 100GB of RAM & "Cart Team" to use only 100CPU and 200GB of RAM, we can use resource quota in kubernetes.

# Resource quotas are defined at namespace level and they limit the total amount of resources that can be consumed by all the pods in that namespace.

# create roboshop-test namespace
apiVersion: v1
kind: Namespace
metadata:
  name: roboshop-test

--- 
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: roboshop-test
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"

--- 
# When you've quotas defined at namespace level, you cannot create pods in that namespace without limits & requests defined in the pod spec. If you try to create a pod without limits & requests, you will get an error like below.
apiVersion: v1
kind: Pod
metadata:
  name: debugger-pod
  namespace: roboshop-test
spec:
  containers:
  - name: debian-c2
    image: alpine/curl:latest
    command: ["sleep", "600"]

# Error from server (Forbidden): error when creating "20-resourceQuota.yml": pods "debugger-pod" is forbidden: 
# failed quota: compute-resources: must specify limits.cpu for: debian-c2; limits.memory for: debian-c2; requests.cpu for: debian-c2; requests.memory for: debian-c2

--- 

apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: roboshop-test
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "8Gi"
        cpu: "16"
      limits:
        memory: "16Gi"
        cpu: "32"
  - name: log-aggregator
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

# Error from server (Forbidden): error when creating "20-resourceQuota.yml": 
#pods "frontend" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=32500m,limits.memory=16512Mi,requests.cpu=16250m,requests.memory=8256Mi, used: limits.cpu=0,limits.memory=0,requests.cpu=0,requests.memory=0, limited: limits.cpu=2,limits.memory=2Gi,requests.cpu=1,requests.memory=1Gi

--- 

apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: roboshop-test
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        memory: "0.1Gi"
        cpu: "0.2"
      limits:
        memory: "0.1Gi"
        cpu: "0.4"
