# Creating a Secret this way is never recommended for production use as here we just supply encoded values
apiVersion: v1
kind: Secret
metadata:
  name: roboshop-secret
type: Opaque
data:
  username: cm9vdAo=
  password: cGFzc3dvcmQxMAo=
