# generate a deployment yaml for cart component# create deployment with nginx as image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: roboshop
    tier: cart
spec:
  # modify replicas according to your case
  replicas: 5
  selector:
    matchLabels:
      tier: cart
  template:
    metadata:
      labels:
        tier: cart
    spec:
      containers:
      - name: cart
        image: public.ecr.aws/w2x3d9u7/roboshop-60/cart:v03
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cart-cm

---
# configMap for cart component
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-cm
data:
  # property-like keys; each key maps to a simple value
  REDIS_HOST: "redis-test.robotshop.fun"
  CATALOGUE_HOST: "catalogue-svc"

---

# create LoadBalancer service ; We can make the service accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: cart-svc
spec:
  selector:
    tier: cart
  ports:
    - protocol: TCP
      port: 8080                 # Service accepts the requests on this port
      targetPort: 8080           # Target port in the pods

---
# HPA for the deployment cart 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
