# generate a deployment yaml for frontend component# create deployment with nginx as image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: roboshop
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: public.ecr.aws/w2x3d9u7/roboshop-60/frontend:v13
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-cm
---
# configMap for frontend component
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
data:
  # property-like keys; each key maps to a simple value
  COMPONENT: "frontend"
---

# create LoadBalancer service ; We can make the service accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80                 # Service accepts the requests on this port
      targetPort: 80           # Target port in the pods
  type: LoadBalancer     

---
# HPA for the deployment frontend 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
