# generate a deployment yaml for user component# create deployment with nginx as image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: roboshop
    tier: user
spec:
  # modify replicas according to your case
  replicas: 5
  selector:
    matchLabels:
      tier: user
  template:
    metadata:
      labels:
        tier: user
    spec:
      containers:
      - name: user
        image: public.ecr.aws/w2x3d9u7/roboshop-60/user:v03
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: user-cm

---
# configMap for user component
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-cm
data:
  # property-like keys; each key maps to a simple value
  REDIS_URL: "redis://redis-test.robotshop.fun:6379"
  MONGO_URL: "mongodb://mongodb-test.robotshop.fun:27017/users"

---
# create LoadBalancer service ; We can make the service accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  selector:
    tier: user
  ports:
    - protocol: TCP
      port: 8080                 # Service accepts the requests on this port
      targetPort: 8080           # Target port in the pods

---
# HPA for the deployment user 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
